image: grafana/grafana:latest
description: Open-source analytics and interactive visualization platform
supplies: ["monitoring"]
environment:
  GF_SECURITY_ADMIN_PASSWORD: "@adminpass@"
network:
  external:
    "@port@": "3000"
volumes:
  data:
    mountpoint: /var/lib/grafana
questions:
  adminpass:
    query: "What password should the Grafana admin user have?"
  port:
    query: "What external port should Grafana listen on?"
    type: port
notes:
  URL:
    value: "http://localhost:@port@"
    type: url
  Login:
    value: "Default username is admin"
