image: traefik:latest
description: Cloud-native application proxy and load balancer
supplies: ["http"]
network:
  external:
    "@port@": "80"
    "@dashport@": "8080"
volumes:
  config:
    mountpoint: /etc/traefik
questions:
  port:
    query: "What external port should Traefik listen on for HTTP traffic?"
    type: port
  dashport:
    query: "What external port should the Traefik dashboard listen on?"
    type: port
notes:
  URL:
    value: "http://localhost:@port@"
    type: url
  Dashboard:
    value: "http://localhost:@dashport@"
    type: url
