image: bitnami/prometheus:latest
environment: {}
network:
  external:
    "@port@": "9090"
  internal: {}
volumes:
  data:
    mountpoint: /opt/bitnami/prometheus/data
  config:
    mountpoint: /opt/bitnami/prometheus/conf
questions:
  port:
    query: "What external port should Prometheus listen on?"
    type: port
notes:
  URL: "http://localhost:@port@"
  Config: "Place prometheus.yml in the config volume"
